// Auto-generated from BASE DE DONNEES DES ETABLISSEMENTS PHARMACEUTIQUES.xlsx
// Total: 496 etablissements

export const ESTABLISHMENTS = [
  {t:"officine",n:"Centrale de Banikoara",d:"Alibori",c:"Banikoara",r:"AFIDJI Kifayatou"},
  {t:"officine",n:"Pharmacie Tawfiq de Sonsoro",d:"Alibori",c:"Kandi",r:"BATA-BORY Cédric Abdoul Fawoaz"},
  {t:"officine",n:"Magnolia",d:"Alibori",c:"Banikoara",r:"Morel Sergio CODO"},
  {t:"officine",n:"Dara Fari (Ex Capitaine FariI)",d:"Alibori",c:"Malanville",r:"Tidjani LEHMAN"},
  {t:"officine",n:"Du Sahel (décès)",d:"Alibori",c:"Malanville",r:"Feu Clement A. LISSANON"},
  {t:"officine",n:"Nasiara",d:"Alibori",c:"Kandi",r:"Raïmi Y. TOGBE"},
  {t:"officine",n:"Nasiara de Kérou",d:"Atacora",c:"Kérou",r:"ADJIBODE Mochébolatan Rodrigue Steeve"},
  {t:"officine",n:"Eden d\'Ourbouga",d:"Atacora",c:"Natitingou",r:"HONVOHESSOU Jean-parphunus Tyrsus"},
  {t:"officine",n:"La Bienheureuse (Natitingou)",d:"Atacora",c:"Natitingou",r:"Bader Bèmpakè N’TCHA"},
  {t:"officine",n:"Tanguiéta",d:"Atacora",c:"Tanguiéta",r:"Francis KOUNAGBE"},
  {t:"officine",n:"Tissanta (Décès)",d:"Atacora",c:"Natitingou",r:"Feu Florent KOUAGOU"},
  {t:"officine",n:"Adanhounsa",d:"Atlantique",c:"Allada",r:"Narcisse GBEDJI décès"},
  {t:"officine",n:"Attogon",d:"Atlantique",c:"Allada",r:"AKLAN CAKPO Nouléhoungbé Martin"},
  {t:"officine",n:"Akassato",d:"Atlantique",c:"Abomey-Calavi",r:"Eléna SMIRNOVA epse GBEMENOU"},
  {t:"officine",n:"La Bénédiction",d:"Atlantique",c:"Abomey-Calavi",r:"KPEKOU Essènandé Zounchemè Venceslas Ernest"},
  {t:"officine",n:"Senan Zounga",d:"Atlantique",c:"Abomey-Calavi",r:"AKELE Armel Aristide Adebayo"},
  {t:"officine",n:"Ayessi Godomey",d:"Atlantique",c:"Abomey-Calavi",r:"CAKPO-CHICHI P. Urbain"},
  {t:"officine",n:"Carrefour Gninnin",d:"Atlantique",c:"Abomey-Calavi",r:"BIO YERIMA B. FIDELE"},
  {t:"officine",n:"Cica Santé Akassato",d:"Atlantique",c:"Abomey-Calavi",r:"DASSEYA N. Roseline"},
  {t:"officine",n:"Cité Arconville",d:"Atlantique",c:"Abomey-Calavi",r:"Wilfrid Didier D. AGBATCHOSSOU"},
  {t:"officine",n:"Cité de paix (HOUEGBO) (Ex Pharmacie Saint Enfant Jesus de Houegbo)",d:"Atlantique",c:"Toffo",r:"AMOUSSOU YEHOUEGNON LOUIS"},
  {t:"officine",n:"Dagbédé de Vassého",d:"Atlantique",c:"Ouidah",r:"ADEOSSI Ronick Landry"},
  {t:"officine",n:"De l\'immaculée Conception",d:"Atlantique",c:"Abomey-Calavi",r:"Pedro E. T. SEKLOKA"},
  {t:"officine",n:"Dèkoungbé",d:"Atlantique",c:"Abomey-Calavi",r:"Firmine KINHA"},
  {t:"officine",n:"Déo Gratias Godomey",d:"Atlantique",c:"Abomey-Calavi",r:"Marthe Aniname SALLAN SOHOUNDE"},
  {t:"officine",n:"Du Campus UAC Sarl",d:"Atlantique",c:"Abomey-Calavi",r:"Marlène T. S. M. KOUDANDE"},
  {t:"officine",n:"Du Château d’eau",d:"Atlantique",c:"Abomey-Calavi",r:"ANIFOWOSHE BELLO Adébissi Sulifath"},
  {t:"officine",n:"Du Lac",d:"Atlantique",c:"Abomey-Calavi",r:"DEDELE Nondomè Victoire Ingrid"},
  {t:"officine",n:"El Béthesda",d:"Atlantique",c:"Allada",r:"Hermine F. AKPAKI BAMODU"},
  {t:"officine",n:"Emmanuel",d:"Atlantique",c:"Abomey-Calavi",r:"Régina E. Irma GNACADJA épouse BADET"},
  {t:"officine",n:"Espace Santé",d:"Atlantique",c:"Abomey-Calavi",r:"Marina Vidova épse ANANI"},
  {t:"officine",n:"Eyitayo de Womey",d:"Atlantique",c:"Abomey-Calavi",r:"Esperance Clémence. E. KAYOSSI"},
  {t:"officine",n:"Fifamè",d:"Atlantique",c:"Abomey-Calavi",r:"KOISSI JOEL FRANCK"},
  {t:"officine",n:"Fleuve de vie",d:"Atlantique",c:"Abomey-Calavi",r:"MOUZOUVI Celia Rosemonde Ablavi"},
  {t:"officine",n:"Gbèna",d:"Atlantique",c:"Ouidah",r:"Christian ATTIGNON"},
  {t:"officine",n:"Godomey Centre",d:"Atlantique",c:"Abomey-Calavi",r:"HESSOU Coffi Pascal"},
  {t:"officine",n:"Godomey Fignonhou",d:"Atlantique",c:"Abomey-Calavi",r:"Céline Raymonde Dossi ZOUNON"},
  {t:"officine",n:"Godomey PK 14",d:"Atlantique",c:"Abomey-Calavi",r:"Claude Mireille CODJIA"},
  {t:"officine",n:"Hèdomey Dekoungbe",d:"Atlantique",c:"Abomey-Calavi",r:"Dèlomè Tchédé VODOUHE"},
  {t:"officine",n:"Hêvié Sarl",d:"Atlantique",c:"Abomey-Calavi",r:"DOHOU Angèle Modupè Epse YEMOA"},
  {t:"officine",n:"Houénoussou",d:"Atlantique",c:"Abomey-Calavi",r:"Valère  Comlan C. AMEGANKPOE"},
  {t:"officine",n:"Iita",d:"Atlantique",c:"Abomey-Calavi",r:"EDAH Alain M. V."},
  {t:"officine",n:"L’Angelus",d:"Atlantique",c:"Abomey-Calavi",r:"Marcelin C.TAKIN"},
  {t:"officine",n:"La Concorde",d:"Atlantique",c:"Abomey-Calavi",r:"Corine DEGLA épse AOUTCHEME"},
  {t:"officine",n:"La Grâce (Ouidah)",d:"Atlantique",c:"Ouidah",r:"Etienne D. OUSSOU"},
  {t:"officine",n:"MERE ELISABETH NOBRE",d:"Atlantique",c:"Ouidah",r:"DAYAROU Botti Bossopa Alice"},
  {t:"officine",n:"La Prunelle de l\'Eternel de PAHOU",d:"Atlantique",c:"Ouidah",r:"LAWAL Abdelaziz"},
  {t:"officine",n:"La Rose",d:"Atlantique",c:"Abomey-Calavi",r:"APLOGAN YEMAN Colombe"},
  {t:"officine",n:"Le Jourdain Togoudo",d:"Atlantique",c:"Abomey-Calavi",r:"Esaïe Moudewhenou MARSHALL"},
  {t:"officine",n:"Le Président",d:"Atlantique",c:"Abomey-Calavi",r:"Bonaventure PADONOU"},
  {t:"officine",n:"Le Schilo (Tankpè-Parana)",d:"Atlantique",c:"Abomey-Calavi",r:"Eunice Labissi KOMI Epse JOHNSON"},
  {t:"officine",n:"Le Sycomore",d:"Atlantique",c:"Abomey-Calavi",r:"BRAHI Olagnidé Georgia Zita"},
  {t:"officine",n:"Les Capucines",d:"Atlantique",c:"Allada",r:"GNINTOUNGBE Linette"},
  {t:"officine",n:"Les Graces Divines de Ouèdo",d:"Atlantique",c:"Abomey-Calavi",r:"MAVOHA Achille"},
  {t:"officine",n:"Magnificat",d:"Atlantique",c:"Abomey-Calavi",r:"LOKO Armelle Mylène"},
  {t:"officine",n:"Maria Gléta",d:"Atlantique",c:"Abomey-Calavi",r:"Noubiowa Conrad B. KOUSSIHOUEDE"},
  {t:"officine",n:"Mitonwè",d:"Atlantique",c:"Ouidah",r:"Gisèle Sicca ELISHA ADJANOHOUN"},
  {t:"officine",n:"Principale de Houéto",d:"Atlantique",c:"Abomey-Calavi",r:"Estelle E. SEWADE"},
  {t:"officine",n:"Principale de Tori Bossito",d:"Atlantique",c:"Tori-Bossito",r:"MARIO BADET"},
  {t:"officine",n:"Saint Abel Pharmabel de Tankpè",d:"Atlantique",c:"Abomey-Calavi",r:"Camille Rock DOMONHEDO"},
  {t:"officine",n:"Saint Antoine de Padoue",d:"Atlantique",c:"Abomey-Calavi",r:"Carine Gwladys MEHOBA"},
  {t:"officine",n:"Saint Bénoît de Womey",d:"Atlantique",c:"Abomey-Calavi",r:"SONDJO Rodrigue Gethaime"},
  {t:"officine",n:"Saint Georges",d:"Atlantique",c:"Abomey-Calavi",r:"Eunice S. D. GOUTON"},
  {t:"officine",n:"Saint Gérard de Zoundja",d:"Atlantique",c:"Abomey-Calavi",r:"Lidwine N. HOUNKPATIN"},
  {t:"officine",n:"Saint Paul",d:"Atlantique",c:"Abomey-Calavi",r:"Aristide S. AKOVOWANOU"},
  {t:"officine",n:"Saint PioTokan",d:"Atlantique",c:"Abomey-Calavi",r:"Anihuvi Nadège BEBADA"},
  {t:"officine",n:"De la Centrale Maria-Gleta 2 (Pharmacie Camp Guézo 2)",d:"Atlantique",c:"Abomey-Calavi",r:"EKUE Axelle Peggy"},
  {t:"officine",n:"Saint Steve Sarl",d:"Atlantique",c:"Abomey-Calavi",r:"ADJEHOUNOU AGBEGBANOU Virginie"},
  {t:"officine",n:"Sainte Adèle de l’Echangeur de Godomey",d:"Atlantique",c:"Abomey-Calavi",r:"Henri Charles AÏNADOU"},
  {t:"officine",n:"Sainte Bernadette",d:"Atlantique",c:"Tori-Bossito",r:"HOUNGNIMY H. Ghislaine Angèle"},
  {t:"officine",n:"Sainte Marie Elise",d:"Atlantique",c:"Abomey-Calavi",r:"Kadi Jacques Francis Régis CHABI CHALLA"},
  {t:"officine",n:"Sainte Trinité de Pahou",d:"Atlantique",c:"Ouidah",r:"Audrey Nina DJENONTIN"},
  {t:"officine",n:"Sèhouè",d:"Atlantique",c:"Toffo",r:"Marius HOUEZE"},
  {t:"officine",n:"Sos Santé",d:"Atlantique",c:"Abomey-Calavi",r:"KOROGONE Edwige Tècle B.S."},
  {t:"officine",n:"Togoudo",d:"Atlantique",c:"Abomey-Calavi",r:"Zacharie BIO YERIMA"},
  {t:"officine",n:"Toussaint L\'ouverture",d:"Atlantique",c:"Allada",r:"GOUMISSI Inès Evita"},
  {t:"officine",n:"Le Lotus",d:"Atlantique",c:"Zè",r:"NONDICHAO Abd-El-Kader Fadil"},
  {t:"officine",n:"Zinvié",d:"Atlantique",c:"Abomey-Calavi",r:"Todèdé Murielle GBAGUIDI"},
  {t:"officine",n:"Zoca",d:"Atlantique",c:"Abomey-Calavi",r:"Gounou Khamel LAFIA"},
  {t:"officine",n:"Zopah Olouwatobi",d:"Atlantique",c:"Abomey-Calavi",r:"OUINSOU HOUENOU Elsie"},
  {t:"officine",n:"Saint Camille",d:"Atlantique",c:"Ouidah",r:"GANMAVO Kuassi Arnaud Gislain"},
  {t:"officine",n:"La Miraculeuse",d:"Atlantique",c:"Ouidah",r:"ADE Nadège Houéfa"},
  {t:"officine",n:"Zoé Santé",d:"Atlantique",c:"Abomey-Calavi",r:"ASSOGBA  Karell Armela Mawoussi"},
  {t:"officine",n:"Olouwatoyin de Kpota",d:"Atlantique",c:"Abomey-Calavi",r:"BELLO Mourchidath-Laye B.A.L"},
  {t:"officine",n:"Zoundja Satellite",d:"Atlantique",c:"Abomey-Calavi",r:"AZA-GNANDJI Afiavi Carmine Nora"},
  {t:"officine",n:"La Référence",d:"Atlantique",c:"Abomey-Calavi",r:"SEÏDOU Anisha"},
  {t:"officine",n:"Alpha Oméga Bazounkpa",d:"Atlantique",c:"Ouidah",r:"AVOKAN Emadin Djomion Esaï"},
  {t:"officine",n:"Alhéri Glodénou",d:"Atlantique",c:"Abomey-Calavi",r:"OSSENI Razack"},
  {t:"officine",n:"Sedami",d:"Atlantique",c:"Abomey-Calavi",r:"HOUETCHEGNON Daagbé Pharanète"},
  {t:"officine",n:"Nouvelle Eve",d:"Atlantique",c:"Zê",r:"VIAKIN KINTOSSOU Comlan Ferdin Marcus"},
  {t:"officine",n:"PHARMACIE AÏTCHEDJI SEMINAIRE",d:"Atlantique",c:"Abomey-Calavi",r:"FADEGNON Gildas Max Kévin"},
  {t:"officine",n:"PHARMACIE VALLEE BERACA",d:"Atlantique",c:"Abomey-Calavi",r:"OKPE Viviane O. B. Kpéléro"},
  {t:"officine",n:"Cité des Kobourou",d:"Borgou",c:"Parakou",r:"KOBA Euloge"},
  {t:"officine",n:"Confiance",d:"Borgou",c:"Parakou",r:"AKOBI Sadia"},
  {t:"officine",n:"Des 3 banques",d:"Borgou",c:"Parakou",r:"ATINDOGBE Raoul"},
  {t:"officine",n:"Kaaya",d:"Borgou",c:"Kalalé",r:"BONOU Nabil"},
  {t:"officine",n:"Don de Dieu (Nikki)",d:"Borgou",c:"Nikki",r:"Abdou Wabi Abdoulaye BACHABI"},
  {t:"officine",n:"Du Campus (Parakou)",d:"Borgou",c:"Parakou",r:"Fortuné Allyou SABI MEKIRE"},
  {t:"officine",n:"Du Lycée",d:"Borgou",c:"Parakou",r:"Maurice Codjo E. ASSOGBA"},
  {t:"officine",n:"Beyerou",d:"Borgou",c:"Parakou",r:"SEDJAME Sèmassa Arlette Bernice"},
  {t:"officine",n:"Saint Benoit de Parakou",d:"Borgou",c:"Parakou",r:"EPOU Wilfried Marius Komi"},
  {t:"officine",n:"Du Plateau",d:"Borgou",c:"Parakou",r:"ALOU SILFATOU"},
  {t:"officine",n:"Ganou  (Ex Guéma)",d:"Borgou",c:"Parakou",r:"Tchinou Diane ALOUKOUTOU"},
  {t:"officine",n:"Houeze Pharma",d:"Borgou",c:"Tchaourou",r:"CHARLES LEBON ASSOGBA"},
  {t:"officine",n:"Imane",d:"Borgou",c:"Parakou",r:"Farid BOURAIMA"},
  {t:"officine",n:"Okedama",d:"Borgou",c:"Parakou",r:"KOUWAKANOU Sèdami Aubierge Arielle"},
  {t:"officine",n:"La Gare",d:"Borgou",c:"Parakou",r:"Janvier Guy ZINZINDOHOUE"},
  {t:"officine",n:"La Grâce (Parakou)",d:"Borgou",c:"Parakou",r:"Roger ADJITORE"},
  {t:"officine",n:"N’dali",d:"Borgou",c:"N\'Dali",r:"AMIDOU Moustapha"},
  {t:"officine",n:"Santé Vitale",d:"Borgou",c:"Parakou",r:"Gil TOSSOU"},
  {t:"officine",n:"Tranza",d:"Borgou",c:"Parakou",r:"Benoît N. DAKOU"},
  {t:"officine",n:"Vita Plus",d:"Borgou",c:"Parakou",r:"Feng Wêi FANG épse ADJITORE"},
  {t:"officine",n:"Zongo II",d:"Borgou",c:"Parakou",r:"Imorou KOUTOUMA ADDA"},
  {t:"officine",n:"Nima",d:"Borgou",c:"Parakou",r:"SARE MIZI Adboulaye"},
  {t:"officine",n:"Nouvelle Pharmacie Albarika",d:"Borgou",c:"Parakou",r:"Alain  GOUDOTE"},
  {t:"officine",n:"Arafat",d:"Borgou",c:"Parakou",r:"AWINDE Aminou Dine"},
  {t:"officine",n:"Banikanni",d:"Borgou",c:"Parakou",r:"Pierre NAGOBA"},
  {t:"officine",n:"Bwendora",d:"Borgou",c:"Bembèrèkè",r:"Rachade Zimé Nakou"},
  {t:"officine",n:"Pharmacie El-Shadday Choukran",d:"Borgou",c:"Parakou",r:"YEMPABOU Alimatou"},
  {t:"officine",n:"Camp Séro Kpéra",d:"Borgou",c:"Parakou",r:"Abdel Wahid BABIO"},
  {t:"officine",n:"Carrefour Hubert K.MAGA",d:"Borgou",c:"Parakou",r:"Martine Mahougnon KOGNONSA"},
  {t:"officine",n:"Agbado",d:"Collines",c:"Savalou",r:"Michel Arnaud AKPAMOLI"},
  {t:"officine",n:"CLEMENT DE TCHETTI",d:"Collines",c:"Savalou",r:"HOUNLIDJI Fasteylah Yeïme"},
  {t:"officine",n:"Bantè",d:"Collines",c:"Bantè",r:"Rodrigue Abiola AGBODJOGBE"},
  {t:"officine",n:"Dassa Carrefour",d:"Collines",c:"Dassa-Zoumè",r:"AGONNOUDE Wilfried"},
  {t:"officine",n:"De la Savane",d:"Collines",c:"Glazoué",r:"Kinti Yassénon ADANDE"},
  {t:"officine",n:"Notre Dame d\'Arigbo",d:"Collines",c:"Dassa-Zoumè",r:"PANOU Jesugo Enagnon Mathilde"},
  {t:"officine",n:"Pharmacie Le Paraclet",d:"Collines",c:"Glazoué",r:"HOUNTONDJI G. Cyriaque"},
  {t:"officine",n:"Des Collines",d:"Collines",c:"Dassa-Zoumè",r:"SALAMI Aliou"},
  {t:"officine",n:"Ireti",d:"Collines",c:"Savè",r:"Houmènou Jules Romuald AKPAKA"},
  {t:"officine",n:"Pharmacie ABE DU MARCHE DE SAVE",d:"Collines",c:"Savè",r:"BAKPE Enagnon Arias"},
  {t:"officine",n:"Lafia Sarl",d:"Collines",c:"Savalou",r:"Tayo Hervé AYEKO"},
  {t:"officine",n:"Oluwa Tobi Kilibo",d:"Collines",c:"OUESSE",r:"DOFLIEN A.Guillaume"},
  {t:"officine",n:"Ouèssè Centre",d:"Collines",c:"OUESSE",r:"SEGLA Boris Igor"},
  {t:"officine",n:"Principale Glazoué",d:"Collines",c:"Glazoué",r:"DANKORO Yacine Séro"},
  {t:"officine",n:"Priorité Santé (Paouignan)",d:"Collines",c:"Dassa-Zoumè",r:"Célestin C. AKOLE"},
  {t:"officine",n:"ASOVIC DE GOUKA",d:"Collines",c:"Bantè",r:"SODOGA Armelle Armandine"},
  {t:"officine",n:"PHARMACIE DONAN DE SAVALOU",d:"Collines",c:"Savalou",r:"LEGBA Mahoutin Eunice"},
  {t:"officine",n:"Gloria Déi de Dogbo Sarl",d:"Couffo",c:"Dogbo",r:"Dognon Yves Constantin BOKO-VOU"},
  {t:"officine",n:"Le Fleuron",d:"Couffo",c:"Aplahoué",r:"BANKOLE Paul Odjouola"},
  {t:"officine",n:"Nouvelle Pharmacie Grace Divine",d:"Couffo",c:"Aplahoué",r:"Rafic Ayinla OBAHORIN"},
  {t:"officine",n:"Lalo Hlassame",d:"Couffo",c:"Lalo",r:"HODE Joachim"},
  {t:"officine",n:"Wezon Aplahoué",d:"Couffo",c:"Aplahoué",r:"KPOVIESSI Kaleb"},
  {t:"officine",n:"Saint Marcel (Azovè)",d:"Couffo",c:"Aplahoué",r:"Félicité Bienvenu GBEDJINOU"},
  {t:"officine",n:"Sainte Carine",d:"Couffo",c:"Klouékanmè",r:"Bienvenu Dékpali SEKPE"},
  {t:"officine",n:"Sainte Véronique de Djakotomey",d:"Couffo",c:"Djakotomey",r:"MADEGNAN Juste"},
  {t:"officine",n:"Rehoboth - P",d:"Couffo",c:"Klouékanmey",r:"GUIDIGAN ZINSOU Assiba Patricia"},
  {t:"officine",n:"DU CARREFOUR TOVIKLIN",d:"Couffo",c:"Toviklin",r:"YAMONTCHE Sandy Lena"},
  {t:"officine",n:"Nouvelle Pharmacie Madina",d:"Donga",c:"Djougou",r:"SALAMI Y. Aichat"},
  {t:"officine",n:"Safari (Bassila)",d:"Donga",c:"Bassila",r:"Adamou KPERA"},
  {t:"officine",n:"Taifa",d:"Donga",c:"Djougou",r:"DANKORO Samia"},
  {t:"officine",n:"Ouaké",d:"Donga",c:"Ouaké",r:"MOUSTAPHA Noua Adeumi Adio Boris"},
  {t:"officine",n:"Du Marché Saint Michel (fermée)",d:"Littoral",c:"Cotonou",r:"TOPANOU ADOLPHE"},
  {t:"officine",n:"Saint Mathieu de l\'Aéroport (fermée)",d:"Littoral",c:"Cotonou",r:"Marcel Koffi HOUNDONOUGBO"},
  {t:"officine",n:"Adechina",d:"Littoral",c:"Cotonou",r:"Edgard PRUDENCIO"},
  {t:"officine",n:"Adetona Lom-Nava",d:"Littoral",c:"Cotonou",r:"Alimatou LAGUIDE SALAMI"},
  {t:"officine",n:"Agbodjedo Sedekon (Ex Lotus Blanc)",d:"Littoral",c:"Cotonou",r:"MEDE ZINSOU MARCELLINE"},
  {t:"officine",n:"Aïdjèdo (Ex-Jeanne d’Arc)",d:"Littoral",c:"Cotonou",r:"Aristide ADJAGBONI"},
  {t:"officine",n:"Akossombo",d:"Littoral",c:"Cotonou",r:"HOUVI Joëlle"},
  {t:"officine",n:"Alafia",d:"Littoral",c:"Cotonou",r:"Ida BADOU née AHO"},
  {t:"officine",n:"Amen",d:"Littoral",c:"Cotonou",r:"ADANKLOUNON Philippe Roland Sèzan."},
  {t:"officine",n:"Atinkanmey",d:"Littoral",c:"Cotonou",r:"Laurence Mireille DENAGNON née MONNOU"},
  {t:"officine",n:"Avotrou",d:"Littoral",c:"Cotonou",r:"Moïbatou MALIKI"},
  {t:"officine",n:"Bien Être",d:"Littoral",c:"Cotonou",r:"DEGBEDJI Carole M."},
  {t:"officine",n:"Bolarin",d:"Littoral",c:"Cotonou",r:"ANJORIN Djemilatou"},
  {t:"officine",n:"Cadjehoun Ex Vodjè",d:"Littoral",c:"Cotonou",r:"MALIKY Zarath Léonie"},
  {t:"officine",n:"Camp Guézo",d:"Littoral",c:"Cotonou",r:"EKUE Annabelle ep Hounkponou"},
  {t:"officine",n:"Ciné Concorde",d:"Littoral",c:"Cotonou",r:"Sofiath TIDJANI"},
  {t:"officine",n:"Cristal Santé Agla Akplomey",d:"Littoral",c:"Cotonou",r:"Lucienne Arsène L. AMOUZOUN"},
  {t:"officine",n:"De L’Aigle Royal",d:"Littoral",c:"Cotonou",r:"NONVIGNON FELICITE"},
  {t:"officine",n:"De la Haie Vive",d:"Littoral",c:"Cotonou",r:"Feu Marouf Raïmi OSSENI"},
  {t:"officine",n:"De la Mosquée Centrale Zongo",d:"Littoral",c:"Cotonou",r:"Anna SAMOILOVA épse PADONOU"},
  {t:"officine",n:"De la Paix",d:"Littoral",c:"Cotonou",r:"Cosme HOUETO"},
  {t:"officine",n:"De l\'Abattoir",d:"Littoral",c:"Cotonou",r:"Moutiatou Abebi TIDJANI épse TOUKOUROU"},
  {t:"officine",n:"De l\'Amitié",d:"Littoral",c:"Cotonou",r:"Jeanne B. AVLESSI"},
  {t:"officine",n:"De l\'Espérance",d:"Littoral",c:"Cotonou",r:"Laure Florence TAIROU épse ADEBO"},
  {t:"officine",n:"DE L\'ETOILE",d:"Littoral",c:"Cotonou",r:"MALICK Raïma.R"},
  {t:"officine",n:"Don de Dieu de (Cotonou)",d:"Littoral",c:"Cotonou",r:"ACHADE Madeleine"},
  {t:"officine",n:"Du Port",d:"Littoral",c:"Cotonou",r:"Ghislaine DJIDJOHO Née LOKO"},
  {t:"officine",n:"Du Rond Point",d:"Littoral",c:"Cotonou",r:"Fatima ALAOFE"},
  {t:"officine",n:"Fèmi",d:"Littoral",c:"Cotonou",r:"Feu Joël DOSSOU - YOVO"},
  {t:"officine",n:"Fidjrossè",d:"Littoral",c:"Cotonou",r:"Léontine IDOHOU"},
  {t:"officine",n:"Fidjrossè Plage",d:"Littoral",c:"Cotonou",r:"Herman Adjèhoda SOSSOU"},
  {t:"officine",n:"Forum Santé",d:"Littoral",c:"Cotonou",r:"TOUKOUROU MARYDIA"},
  {t:"officine",n:"Ganhi",d:"Littoral",c:"Cotonou",r:"Amèdéssè Ataéna Christiane DOSSOU"},
  {t:"officine",n:"Gbèdjromédé",d:"Littoral",c:"Cotonou",r:""},
  {t:"officine",n:"Gbégamey Ex CCB",d:"Littoral",c:"Cotonou",r:"Abiba BATOKO épse YACOUBOU"},
  {t:"officine",n:"Gratias Minontchou",d:"Littoral",c:"Cotonou",r:"Lynda Eburé Joanita SANTOS"},
  {t:"officine",n:"La Prophétie",d:"Littoral",c:"Cotonou",r:"GBAGUIDI SEMILINKO ANGELIQUE"},
  {t:"officine",n:"Hounchédé",d:"Littoral",c:"Cotonou",r:"Justin NOUDEDJI"},
  {t:"officine",n:"Jak Alédjo",d:"Littoral",c:"Cotonou",r:"Bilikissou Madéjèbi IBOURAÏMA"},
  {t:"officine",n:"Jericho",d:"Littoral",c:"Cotonou",r:"AMOUSSOU H. JOSEPH"},
  {t:"officine",n:"Jonquet",d:"Littoral",c:"Cotonou",r:"Abou Bakr Sidikh JOACHIM"},
  {t:"officine",n:"Kindonou",d:"Littoral",c:"Cotonou",r:"Alfred DAVAKAN"},
  {t:"officine",n:"L\'Eternité",d:"Littoral",c:"Cotonou",r:"Edna Francine ALAPINI"},
  {t:"officine",n:"L’Immaculée Adogléta Ex La Colombe",d:"Littoral",c:"Cotonou",r:"Ayaba Murielle Florie E. J. ZOUNON"},
  {t:"officine",n:"La Béninoise",d:"Littoral",c:"Cotonou",r:"Maroufatou ADJIBI epse ZOUMAROU"},
  {t:"officine",n:"La destinée Sènadé",d:"Littoral",c:"Cotonou",r:"PARAISO I. Lisette Epouse TIDJANI"},
  {t:"officine",n:"La Madone",d:"Littoral",c:"Cotonou",r:"Joëlle Isabelle Adéchoubou HOUNDETE"},
  {t:"officine",n:"Le Conseil Ex Phcie la Fraternité",d:"Littoral",c:"Cotonou",r:"FAGBEMI ABDEL AZIZ"},
  {t:"officine",n:"Le Nokoué",d:"Littoral",c:"Cotonou",r:"Hermine AGBOTON DANDJINOU"},
  {t:"officine",n:"Le Remède",d:"Littoral",c:"Cotonou",r:"Kamal Dine MOUTAÏROU"},
  {t:"officine",n:"Le Rocher",d:"Littoral",c:"Cotonou",r:"SAVI-ELENGA P. Jacqueline"},
  {t:"officine",n:"Le Tamaya",d:"Littoral",c:"Cotonou",r:"Sika GABA-NELU épse AKPETE"},
  {t:"officine",n:"Esplanade Dantokpa (Ex Des 4 Thérapies)",d:"Littoral",c:"Cotonou",r:"Elyse Ablavi ACHANHOUIN KINKINGNEHUN"},
  {t:"officine",n:"Les Archanges",d:"Littoral",c:"Cotonou",r:"Oscar AKOGBETO"},
  {t:"officine",n:"Les Maristes",d:"Littoral",c:"Cotonou",r:"AMOUSSOU Fleurette"},
  {t:"officine",n:"Les pylônes",d:"Littoral",c:"Cotonou",r:"EZIN Edith Joelle ep SOOHOU"},
  {t:"officine",n:"Luli Luli Sarl",d:"Littoral",c:"Cotonou",r:"Alexandre Boco DJEDJI"},
  {t:"officine",n:"Mahuena",d:"Littoral",c:"Cotonou",r:"Grâce VARANGO"},
  {t:"officine",n:"Mahuton",d:"Littoral",c:"Cotonou",r:"Nagoba Hermione Ruth"},
  {t:"officine",n:"Marina Ex Sikècodji",d:"Littoral",c:"Cotonou",r:"COOVI LISETTE CORINE"},
  {t:"officine",n:"Midombo",d:"Littoral",c:"Cotonou",r:"Zomalètho Gisèle  AÏHONNOU"},
  {t:"officine",n:"Nouvelle Pharmacie Agontikon",d:"Littoral",c:"Cotonou",r:"SOUMAILA ADJIBADE M.Kolawolé"},
  {t:"officine",n:"Nouvelle Pharmacie Akogbato",d:"Littoral",c:"Cotonou",r:"LAFIA BORO LAINATOU GNANKI"},
  {t:"officine",n:"Nouvelle Pharmacie Ayélawadjè",d:"Littoral",c:"Cotonou",r:"Raoufi TOUKOUROU"},
  {t:"officine",n:"Nouvelle Pharmacie Dantokpa",d:"Littoral",c:"Cotonou",r:"AMADJI Sèflimi Natalie Guillaumovna"},
  {t:"officine",n:"Nouvelle Pharmacie de l\'Habitat",d:"Littoral",c:"Cotonou",r:"YOUSSOUF RANIA OLAYIDE"},
  {t:"officine",n:"Nouvelle pharmacie Fifadji",d:"Littoral",c:"Cotonou",r:"DANDJINOU Maëlle"},
  {t:"officine",n:"Nouvelle Pharmacie Houéyiho",d:"Littoral",c:"Cotonou",r:"YEDOMON BRICE HERVE"},
  {t:"officine",n:"Nouvelle pharmacie Les Cocotiers",d:"Littoral",c:"Cotonou",r:"BABADAN Kpodji Rodrigue"},
  {t:"officine",n:"Nouvelle Pharmacie Ménontin",d:"Littoral",c:"Cotonou",r:"BIO OBEGUI Iliassou"},
  {t:"officine",n:"Nouvelle Pharmacie Saint Michel",d:"Littoral",c:"Cotonou",r:"Féliciene Fa Ndiaye DIENG épouse SOSSOU"},
  {t:"officine",n:"Océane",d:"Littoral",c:"Cotonou",r:"Arlette Anicette BALLEY"},
  {t:"officine",n:"Okpè Oluwa",d:"Littoral",c:"Cotonou",r:"KARENE SONON DJAÏTO"},
  {t:"officine",n:"Oladjouan",d:"Littoral",c:"Cotonou",r:"LADJOUHAN Ziad Zizi"},
  {t:"officine",n:"Palace Plus",d:"Littoral",c:"Cotonou",r:"René Patrick HOUETO"},
  {t:"officine",n:"Principale (Cotonou)",d:"Littoral",c:"Cotonou",r:"Gisèle Félicité GRIMAUD"},
  {t:"officine",n:"Reine des Grâces",d:"Littoral",c:"Cotonou",r:"Mireille Joëlle AHOYO épse da-SIILVA"},
  {t:"officine",n:"Renouveau",d:"Littoral",c:"Cotonou",r:"Charlotte H. Hortense AKPOVO"},
  {t:"officine",n:"Sacré-cœur",d:"Littoral",c:"Cotonou",r:"Odette Deka Vodjo de-CHACUS CHANKOUIN"},
  {t:"officine",n:"Safari Agla",d:"Littoral",c:"Cotonou",r:"BAGNAN Samira"},
  {t:"officine",n:"Saint Etienne d\'Agla",d:"Littoral",c:"Cotonou",r:"ABIOU Immaculée Grâce Médéssè"},
  {t:"officine",n:"Saint Gabriel",d:"Littoral",c:"Cotonou",r:"Francine AKITOYE LAWANI"},
  {t:"officine",n:"Saint Jean",d:"Littoral",c:"Cotonou",r:"Feu Dominique Justin d\'ALMEIDA"},
  {t:"officine",n:"Saint Joseph",d:"Littoral",c:"Cotonou",r:"Solange Régina IDOHOU"},
  {t:"officine",n:"Saint Louis",d:"Littoral",c:"Cotonou",r:"Sylvianne Monique Bertille AGONHESSOU"},
  {t:"officine",n:"Saint Martin",d:"Littoral",c:"Cotonou",r:"Angèle M. HOUESSINON"},
  {t:"officine",n:"Saint Raphaël du nouveau pont",d:"Littoral",c:"Cotonou",r:"NAGO Murielle"},
  {t:"officine",n:"Saint Urbain",d:"Littoral",c:"w",r:"ZOMAHOUN Karelle"},
  {t:"officine",n:"Sainte Euphrasie de Vossa",d:"Littoral",c:"Cotonou",r:"Fifamin Charlène Inès ADEOSSI"},
  {t:"officine",n:"Sainte Famille",d:"Littoral",c:"Cotonou",r:"Ida AHIVODJI"},
  {t:"officine",n:"Sainte Foi",d:"Littoral",c:"Cotonou",r:"Claudette DOMINGO"},
  {t:"officine",n:"Sainte Madelaine Zogbohouè",d:"Littoral",c:"Cotonou",r:"Dr Corine ZEHE"},
  {t:"officine",n:"Sainte Philomène",d:"Littoral",c:"Cotonou",r:"WHANNOU Ep DOUVI Eloïse Constance"},
  {t:"officine",n:"Sainte Rita (Ex Pharmacie de l\'espoir)",d:"Littoral",c:"Cotonou",r:"Audrey ABALO"},
  {t:"officine",n:"Nouvelle Pharmacie Sainte Victoire",d:"Littoral",c:"Cotonou",r:"Farhid Honorat ADETONAH"},
  {t:"officine",n:"Sainteté à l\'Eternel",d:"Littoral",c:"Cotonou",r:"MEGNIGBETO O.Thècle Léa"},
  {t:"officine",n:"Salem Hlazounto",d:"Littoral",c:"Cotonou",r:"Esther Diana Dédévi AJAVON"},
  {t:"officine",n:"Sègbèya",d:"Littoral",c:"Cotonou",r:"Raphaël DEGBEDJI"},
  {t:"officine",n:"Suru Léré (Ex Ancien Pont)",d:"Littoral",c:"Cotonou",r:"Ayichatou CHITOU OSSENI"},
  {t:"officine",n:"Tanto le Joker",d:"Littoral",c:"Cotonou",r:"Hans Lucas AGBODJINOU"},
  {t:"officine",n:"Vèdoko",d:"Littoral",c:"Cotonou",r:"Cyrille AHOSSI"},
  {t:"officine",n:"Vie et santé",d:"Littoral",c:"Cotonou",r:"Victoire AGBIDINOUKOUN épse SEGLA"},
  {t:"officine",n:"Vie Nouvelle",d:"Littoral",c:"Cotonou",r:"HENADOU Martin"},
  {t:"officine",n:"Vogue",d:"Littoral",c:"Cotonou",r:"Rissi SOUMANOU ADJIBADE"},
  {t:"officine",n:"Yénawa",d:"Littoral",c:"Cotonou",r:"Romain Pamphille AHOUANGNIVO"},
  {t:"officine",n:"Zogbo",d:"Littoral",c:"Cotonou",r:"Emma ABOKI"},
  {t:"officine",n:"Zongo",d:"Littoral",c:"Cotonou",r:"Prosper AHONLONSOU"},
  {t:"officine",n:"Zongo Nima",d:"Littoral",c:"Cotonou",r:"JOACHIM ANIFATH"},
  {t:"officine",n:"Siloé Dégakon",d:"Littoral",c:"Cotonou",r:"BANKOLE Marc Moboladji"},
  {t:"officine",n:"Grande Pharmacie de Comè Sarl",d:"Mono",c:"Comè",r:"Fabrice Kadjogbé ODJARADO"},
  {t:"officine",n:"Eyram",d:"Mono",c:"Bopa",r:"ATOUN Adjidokpa Gloria Suzanne"},
  {t:"officine",n:"Hillacondji Don de Dieu (Ex Notre Dame du perpétuel secours)",d:"Mono",c:"Grand-Popo",r:"ADEGBIDIN A. Mahfouz"},
  {t:"officine",n:"La Nériad",d:"Mono",c:"Comè",r:"MADOKPON Mêgnissè"},
  {t:"officine",n:"Sainte Marie Reine",d:"Mono",c:"Lokossa",r:"ASSANH Jean Marie Codjovi"},
  {t:"officine",n:"Le Bon Samaritain",d:"Mono",c:"Lokossa",r:"Ernest DOSSOU"},
  {t:"officine",n:"Le Carrefour de Grand-Popo",d:"Mono",c:"Grand-Popo",r:"D\'ALMEIDA BENNO"},
  {t:"officine",n:"Nouvelle Pharmacie  Zogbédji",d:"Mono",c:"Lokossa",r:"BAH TASSOU BAGNAN"},
  {t:"officine",n:"Principale de Sè",d:"Mono",c:"Houéyogbé",r:"BELLO MOUHAMED FAROUK"},
  {t:"officine",n:"Sahouè",d:"Mono",c:"Houéyogbé",r:"Sochi Marie HOUNSOU"},
  {t:"officine",n:"Sainte Croix (Comè)",d:"Mono",c:"Comè",r:"AZONDEKON AKUAVI JANICE"},
  {t:"officine",n:"Adjarra Docodji UPAO",d:"Ouémé",c:"Porto-Novo",r:"FAGBEMI Joel Martial"},
  {t:"officine",n:"Adjibade Sarl",d:"Ouémé",c:"Porto-Novo",r:"SOUMAILA ADJIBADE IKILILOU ADEWALE"},
  {t:"officine",n:"Adouni",d:"Ouémé",c:"Akpro-Missérété",r:"Farihath Hermione ASSOGBA"},
  {t:"officine",n:"Agata Grace Divine",d:"Ouémé",c:"Adjarra",r:"Abègnonhou Mariane Elodie HONFOGA"},
  {t:"officine",n:"Agblangandan",d:"Ouémé",c:"Sèmè-Kpodji",r:"Madinatou DENDE BADIROU"},
  {t:"officine",n:"Agbokou",d:"Ouémé",c:"Porto-Novo",r:"Adéline Valérie AGBOTON"},
  {t:"officine",n:"Badirou de Tchinvié",d:"Ouémé",c:"Porto-Novo",r:"ADJIBADE BADIROU Izbath Armelle"},
  {t:"officine",n:"Boladji",d:"Ouémé",c:"Porto-Novo",r:"Safiatou  Y. BAKARY"},
  {t:"officine",n:"Carrefour Gbodjè",d:"Ouémé",c:"Porto-Novo",r:"Malick ADJIBOLA"},
  {t:"officine",n:"Catchi",d:"Ouémé",c:"Porto-Novo",r:"ADEBO Naïlath Akankè Imelda"},
  {t:"officine",n:"Centrale d’Adjarra",d:"Ouémé",c:"Adjarra",r:"KEKE Agossou Cyprien"},
  {t:"officine",n:"Centrale Kokoyè",d:"Ouémé",c:"Porto-Novo",r:"C. ZOMAHOUN"},
  {t:"officine",n:"Cristal Dodji",d:"Ouémé",c:"Porto-Novo",r:"Christophe Elie ODJO"},
  {t:"officine",n:"De la Vallée de l’Ouémé",d:"Ouémé",c:"Adjohoun",r:"Gisèle Lydie LISSANON VODEME"},
  {t:"officine",n:"Hounsa Rehoboth",d:"Ouémé",c:"Porto-Novo",r:"Déo - Gratias AMOUSSOU"},
  {t:"officine",n:"Djeffa",d:"Ouémé",c:"Sèmè-Kpodji",r:"GOUNOU Solange"},
  {t:"officine",n:"Djegan Kpevi",d:"Ouémé",c:"Porto-Novo",r:"Mohamed Kèfil SOUNKERE"},
  {t:"officine",n:"Dona - Déï",d:"Ouémé",c:"Sèmè-Kpodji",r:"Jean - Marie TOKOUDAGBA"},
  {t:"officine",n:"Dona (Porto - Novo)",d:"Ouémé",c:"Porto-Novo",r:"Mathias SOUDE"},
  {t:"officine",n:"Dowa",d:"Ouémé",c:"Porto-Novo",r:"Cyr Marceau Pierre GBESSOU"},
  {t:"officine",n:"Dowa Gbago Tabita",d:"Ouémé",c:"Porto-Novo",r:"HOUNTOTEGBE Sandrine Tatiana"},
  {t:"officine",n:"Du Boulevard Djassin",d:"Ouémé",c:"Porto-Novo",r:"Ismahinl ONIFADE"},
  {t:"officine",n:"Ekpè",d:"Ouémé",c:"Sèmè-Kpodji",r:"AHOLOUKPE Z. REMI"},
  {t:"officine",n:"Fontaine de Jouvence",d:"Ouémé",c:"Sèmè-Kpodji",r:"ALAVO Nadège"},
  {t:"officine",n:"Grande Pharmacie Krake",d:"Ouémé",c:"Sèmè-Kpodji",r:"TOSSOU Emmanuel Yaovi"},
  {t:"officine",n:"Koutongbé (Ex National)",d:"Ouémé",c:"Porto-Novo",r:"Yacoubou Abioye ADJE"},
  {t:"officine",n:"Kpèdétin",d:"Ouémé",c:"Akpro-Missérété",r:"Jonas L.TOUDONOU"},
  {t:"officine",n:"La Jouvence Tokpota Dadjrougbe",d:"Ouémé",c:"Porto-Novo",r:"DASSOU Morel Enamboua"},
  {t:"officine",n:"La Place Kokoye",d:"Ouémé",c:"Porto-Novo",r:"ZOMAHOUN Carène"},
  {t:"officine",n:"Le Prestige du Pont",d:"Ouémé",c:"Porto-Novo",r:"TAIROU Kazirath Mariette Bimbola"},
  {t:"officine",n:"Adjohoun",d:"Ouémé",c:"Adjohoun",r:"RAÏMI Abebi Nawal"},
  {t:"officine",n:"Les Anges",d:"Ouémé",c:"Dangbo",r:"Jules D. OUSSOUGOE"},
  {t:"officine",n:"Les Chérubins",d:"Ouémé",c:"Sèmè-Kpodji",r:"K. Régis Michaël AMEGEE"},
  {t:"officine",n:"Les Palmiers",d:"Ouémé",c:"Porto-Novo",r:"Mystoura AKPLOGAN"},
  {t:"officine",n:"L\'Harmonie",d:"Ouémé",c:"Sèmè-Kpodji",r:"LIADY Suad"},
  {t:"officine",n:"L\'unité",d:"Ouémé",c:"Porto-Novo",r:"Raïma ODJO"},
  {t:"officine",n:"Malanhoui",d:"Ouémé",c:"Adjarra",r:"AHOKPOSSI Narcisse"},
  {t:"officine",n:"Metogninsè d\'Anavié S.A.S",d:"Ouémé",c:"Porto-Novo",r:"OLLO A. DENAMI ELVIRE"},
  {t:"officine",n:"Notre Dame de l\'Atlantique Akondé",d:"Ouémé",c:"SEME-KPODJI",r:"Blaise KOUDOGBO"},
  {t:"officine",n:"Nouvel Espoir (Ex victoria)",d:"Ouémé",c:"Avrankou",r:"Eusèbe D. AGONKPAHOUN"},
  {t:"officine",n:"Nouvel Horizon",d:"Ouémé",c:"Sèmè-Kpodji",r:"Eugène DEGUENON"},
  {t:"officine",n:"Nouvelle Pharmacie Du Grand Marché",d:"Ouémé",c:"Porto-Novo",r:"HOUNDJO Gylchrist Gildas Sègla"},
  {t:"officine",n:"Nouvelle Pharmacie Kandévié",d:"Ouémé",c:"Porto-Novo",r:"CHOGNIKA DONKAIRE II"},
  {t:"officine",n:"Oganla",d:"Ouémé",c:"Porto-Novo",r:"Léopoldine da - SILVA"},
  {t:"officine",n:"Olatoundji",d:"Ouémé",c:"Porto-Novo",r:"Saliou LATOUNDJI"},
  {t:"officine",n:"Olayèmi Guévié",d:"Ouémé",c:"Porto-Novo",r:"HOUETO Olayèmi Lydie"},
  {t:"officine",n:"Owodé",d:"Ouémé",c:"Porto-Novo",r:"AVODE Nadège"},
  {t:"officine",n:"Place Bayol",d:"Ouémé",c:"Porto-Novo",r:"Charlemagne AHOUANDJINOU"},
  {t:"officine",n:"Saint Pierre de Sèmè Kpodji",d:"Ouémé",c:"Sèmè-Kpodji",r:"SABI BOUN Saidou"},
  {t:"officine",n:"Saint Raymond du Marché Agata",d:"Ouémé",c:"Porto-Novo",r:"CAPO CHICHI AGBOTON Clotilde"},
  {t:"officine",n:"Sainte Marie",d:"Ouémé",c:"Porto-Novo",r:"Chantal Sylvie ALLADAYE"},
  {t:"officine",n:"Suru Léré (Porto - Novo)",d:"Ouémé",c:"Porto-Novo",r:"Virginie GBADAMASSI"},
  {t:"officine",n:"Toffa 1er",d:"Ouémé",c:"Porto-Novo",r:"Appoline AGBENONCI"},
  {t:"officine",n:"Tohouè",d:"Ouémé",c:"Sèmè-Kpodji",r:"Ashiat AJILEYE"},
  {t:"officine",n:"Tokpota 2 - Davo",d:"Ouémé",c:"Porto-Novo",r:"Sidikath M.M.   SAÏZONOU épse SAGBO"},
  {t:"officine",n:"Vakon",d:"Ouémé",c:"Akpro-Missérété",r:"MIKODE Hermione"},
  {t:"officine",n:"Val des Graces Sarl",d:"Ouémé",c:"Sèmè-Kpodji",r:"Syadath Suruléré Omoniyi BOURAÏMA"},
  {t:"officine",n:"Vêkpa",d:"Ouémé",c:"Porto-Novo",r:"Moustapha Ibrahim ABLOH"},
  {t:"officine",n:"Sèdjro de Ouanho",d:"Ouémé",c:"Avrankou",r:"HEDOKINGBE Ferdinand Sourou"},
  {t:"officine",n:"Sanite Anne",d:"Ouémé",c:"Porto-Novo",r:"AGBATCHOSSOU Dognon Aristide Eric Ahodédji"},
  {t:"officine",n:"du Cinquantenaire Adjakahoué",d:"Ouémé",c:"Porto-Novo",r:"ODJO ZOSSOU Princia Ninette Douce B.D."},
  {t:"officine",n:"Miracle de Tanzoun",d:"Ouémé",c:"Avrankou",r:"QUENUM Jesumin Rébécca Hermance"},
  {t:"officine",n:"Achimi",d:"Plateau",c:"Sakété",r:"ACHIMI Akamni Tohydi"},
  {t:"officine",n:"Enoryves",d:"Plateau",c:"Pobè",r:"Ester EYE"},
  {t:"officine",n:"Adja-Ouèrè",d:"Plateau",c:"Adja-Ouèrè",r:"OLOUSSOKPE Anwaarath Morènikè Agnikè Bérengère"},
  {t:"officine",n:"La Frontière (Igolo)",d:"Plateau",c:"Ifangni",r:"Armand Mohammed Randolph VIOU"},
  {t:"officine",n:"La Grâce Divine Pobè",d:"Plateau",c:"Pobè",r:"Dieudonnée A. GBEZENOU"},
  {t:"officine",n:"Olabissi",d:"Plateau",c:"Sakété",r:"Olabissi Pancras ELEGBEDE"},
  {t:"officine",n:"Principale de Kétou",d:"Plateau",c:"Kétou",r:"Dèhoumon Louis  KOUKPEMEDJI"},
  {t:"officine",n:"Carrefour Y de Igolo",d:"Plateau",c:"Ifangni",r:"SANNI Chouïbou"},
  {t:"officine",n:"Azally II",d:"Zou",c:"Abomey",r:"Carla Maria Josefa Mendes épse AKPAMOLI"},
  {t:"officine",n:"Du Marché Abomey",d:"Zou",c:"Abomey",r:"Victor Léopold MARTIN"},
  {t:"officine",n:"Nouvelle Pharmacie Goho",d:"Zou",c:"Abomey",r:"AYENON Oladé Martial"},
  {t:"officine",n:"Saint Luc de Djimè",d:"Zou",c:"Abomey",r:"Eddy Z. GNACADJA"},
  {t:"officine",n:"Royale d\'Abomey",d:"Zou",c:"Abomey",r:"LALEYE Kolawolé Gilbert Gracieux"},
  {t:"officine",n:"DES MUSEES D\'ABOMEY",d:"Zou",c:"ABOMEY",r:"DOSSA Mirabelle Eunice Mawuena"},
  {t:"officine",n:"Nontinmin",d:"Zou",c:"Agbangnizoun",r:"Nadège A.D.M.E. ZOGO épse DADOUDA ESSE"},
  {t:"officine",n:"Pharmacie Saint Edmond d\'Agbangnizoun",d:"Zou",c:"Agbangnizoun",r:"ZINSOU Dona Ophra Aude"},
  {t:"officine",n:"Ave Maria Carrefour Zakpo",d:"Zou",c:"Bohicon",r:"AMOUSSOU Nathalie Gisèle"},
  {t:"officine",n:"Azonnigbo",d:"Zou",c:"Bohicon",r:"GOUDOTE Rachel (Feu Joseph GOUDOTE)"},
  {t:"officine",n:"Etoile de Kpokon",d:"Zou",c:"Bohicon",r:"NONONSI Bertrand"},
  {t:"officine",n:"Houéfa de Sodohoué",d:"Zou",c:"Bohicon",r:"KADJA Berthe Aurore"},
  {t:"officine",n:"Midokpo",d:"Zou",c:"Bohicon",r:"Joseph OGOUA"},
  {t:"officine",n:"Saint Henri",d:"Zou",c:"Bohicon",r:"Isabelle Marguerite DEGLA"},
  {t:"officine",n:"Sainte Face",d:"Zou",c:"Bohicon",r:"HOUETO Nadia Lisette Sènandé"},
  {t:"officine",n:"PHARMACIE SHALOM",d:"Zou",c:"Bohicon",r:"KOUSSEMOU Reine Pascaline"},
  {t:"officine",n:"SAINTE VALENTINE",d:"Zou",c:"Bohicon",r:"MONTCHO Gbessou Eugène Gualbert"},
  {t:"officine",n:"CŒUR D\'OR",d:"Zou",c:"Bohicon",r:"ALLADAYE Messèton Gertrude Pamela"},
  {t:"officine",n:"Layo de Covè",d:"Zou",c:"Covè",r:"Expédit SONOUNAMETO"},
  {t:"officine",n:"Wahouédon",d:"Zou",c:"Covè",r:"MAMOUNOU MASSARI Orou Kinnou Abdel Kamel"},
  {t:"officine",n:"Péniel de Djidja",d:"Zou",c:"Djidja",r:"Obassandjo F. Benoît TAO"},
  {t:"officine",n:"PHARMACIE PÔLE SANTE",d:"Zou",c:"Djidja",r:"MONHOUNSO Maxime Stanislas"},
  {t:"officine",n:"Zoé d\'Atrokpocodji",d:"Atlantique",c:"Abomey-Calavi",r:"AHOVEGBE Lucrèce Yémalin Judith"},
  {t:"officine",n:"Mathys",d:"Littoral",c:"Cotonou",r:"DEGBE Tofodji Habib"},
  {t:"officine",n:"Zama Bani",d:"Donga",c:"Djougou",r:"AHOUANSOU A. Maxime"},
  {t:"officine",n:"Gorobani",d:"Borgou",c:"Parakou",r:"FASSINOU Agathe Corine Lucresse"},
  {t:"officine",n:"La guérison fin goudron Boni Yayi",d:"Borgou",c:"Parakou",r:"AÏKPON Romaric Abraham"},
  {t:"officine",n:"Pahou Capot",d:"Atlantique",c:"Abomey-Calavi",r:"DOGUE Horus Axel Cokou"},
  {t:"officine",n:"Cité des Bangana",d:"Atacora",c:"Kouandé",r:"N\'OUENI Kanditcha"},
  {t:"officine",n:"Centrale de Houègbo",d:"Atlantique",c:"Toffo",r:"Dr Sèkandé Holonou Jules TAVI"},
  {t:"officine",n:"Hôtel de Ville",d:"Mono",c:"Comè",r:"Edwige Francisca NONO KEN\'GNE Epouse HODE"},
  {t:"officine",n:"DJIDJOHO",d:"Ouémé",c:"Porto-Novo",r:"ZOUNMENOU Mahudo Yabo Aurelle"},
  {t:"officine",n:"DHANVANTARI MA",d:"Alibori",c:"Kandi",r:"DOSSOU Armandine Légère"},
  {t:"officine",n:"LYCEE TECHNIQUE D\'AKASSATO",d:"Atlantique",c:"Abomey-Calavi",r:"ALAOFE Hafsatou Olafèmi"},
  {t:"officine",n:"COPARGO",d:"Donga",c:"Copargo",r:"DONOUMASSOU Roland Irénée"},
  {t:"officine",n:"PHARMACIE PRIELLE DE TINDJI",d:"Zou",c:"Zakpota",r:"BOKODAHO Yénoukoumè Diane Narèche"},
  {t:"officine",n:"LE FIGUIER",d:"Atlantique",c:"Abomey-Calavi",r:"Angelot Paul Z. AHOUANSE"},
  {t:"officine",n:"Zakpota",d:"Zou",c:"Zakpota",r:"HOUESSOU Sètondji Boris Fiacre"},
  {t:"officine",n:"ALAFIA PLUS",d:"Borgou",c:"N\'Dali",r:"SALAMI Mochtar"},
  {t:"officine",n:"Zogbodomey",d:"Zou",c:"Zogbodomey",r:"May Inès Priscille ADOGNIBO"},
  {t:"officine",n:"KAYOSSI",d:"Ouémé",c:"SEME-KPODJI",r:"HESSOU Claudine"},
  {t:"officine",n:"CLEMENT",d:"Donga",c:"Djougou",r:"ADANLIN Lissanon Sètondé Doriane"},
  {t:"officine",n:"IFEDE ROUTE DE KETONOU",d:"Ouémé",c:"SEME-KPODJI",r:"BOURAÏMA Atchabi Raiyath-Laï"},
  {t:"officine",n:"TIBONA",d:"Borgou",c:"Parakou",r:"BADAROU Mohamed Hamad Adjao"},
  {t:"officine",n:"DIVINE MISÉRICORDE DE AKODEHA",d:"Mono",c:"Comè",r:"TCHONLIN Didier"},
  {t:"officine",n:"Pharmacie OASIS",d:"Atlantique",c:"Abomey-Calavi",r:"Dr Ikouchika Fabrice IOUIKOTAN"},
  {t:"officine",n:"Vie Sacrée de Agbato",d:"Littoral",c:"Cotonou",r:"Dr Diane EHOUMI"},
  {t:"officine",n:"ZOUNGBONOU",d:"Mono",c:"Houeyogbé",r:"Dr Farouk COLES"},
  {t:"officine",n:"CENTRALE DE KPOMASSE",d:"Atlantique",c:"KPOMASSE",r:"Dr SOSSA Kafoui Alexandrine"},
  {t:"officine",n:"JACK & CIE",d:"Atlantique",c:"Abomey-Calavi",r:"Dr Godfried T. DOUGNON"},
  {t:"officine",n:"DE L\'ATACORA",d:"Atacora",c:"Natitingou",r:"Dr Eddy OUENDO"},
  {t:"officine",n:"NOUVELLE PHARMACIE DONA DEÏ",d:"Ouémé",c:"Sèmè-Kpodji",r:"Marie Louise GBEDJINOU"},
  {t:"officine",n:"AITCHEDJI SEMINAIRE",d:"Atlantique",c:"Abomey-Calavi",r:""},
  {t:"officine",n:"PHARMACIE LOUHO",d:"Ouémé",c:"Porto-Novo",r:""},
  {t:"officine",n:"PHARMACIE SAINT MARTIN",d:"Littoral",c:"Cotonou",r:"Dr Marie-Angèle HOUESSINON Née GBAGUIDI"},
  {t:"officine",n:"PHARMACIE SURU-LERE",d:"Littoral",c:"Cotonou",r:"Dr Ayichatou CHITOU"},
  {t:"officine",n:"PHARMACIE TISSANTA",d:"Atacora",c:"Natitingou",r:"Néant"},
  {t:"officine",n:"PHARMACIE NA SIARA DE KEROU",d:"Atacora",c:"Kérou",r:""},
  {t:"officine",n:"PHARMACIE LA BIENHEUREUSE",d:"Atacora",c:"Natitingou",r:""},
  {t:"officine",n:"PHARMACIES CLEMENT DE PARTAGO",d:"Donga",c:"Djougou",r:""},
  {t:"officine",n:"PHARMACIE TANGUIETA",d:"Atacora",c:"Tanguiéta",r:""},
  {t:"grossiste",n:"GAPOB COTONOU",d:"Littoral",c:"COTONOU",r:""},
  {t:"grossiste",n:"GAPOB BOHICON",d:"Zou",c:"BOHICON",r:"Dr NONONSI Bertrand"},
  {t:"grossiste",n:"GAPOB PARAKOU",d:"Borgou",c:"PARAKOU",r:""},
  {t:"grossiste",n:"LABOREX BENIN",d:"Littoral",c:"COTONOU",r:"Dr Maria DARANKOUM"},
  {t:"grossiste",n:"UBIPHARM BENIN",d:"Littoral",c:"COTONOU",r:""},
  {t:"grossiste",n:"UBPHAR COTONOU",d:"",c:"",r:""},
  {t:"grossiste",n:"UBPHAR PORTO-NOVO",d:"",c:"",r:""},
  {t:"grossiste",n:"UBPHAR PARAKOU",d:"Borgou",c:"PARAKOU",r:"Dr Diane BATIA"},
  {t:"grossiste",n:"SoBAPS DG",d:"Littoral",c:"COTONOU",r:""},
  {t:"grossiste",n:"SoBAPS AGENCE COTONOU",d:"",c:"",r:""},
  {t:"grossiste",n:"SoBAPS AGENCE PARAKOU",d:"Borgou",c:"PARAKOU",r:"Dr Steve DOSSOU-YOVO"},
  {t:"grossiste",n:"SoBAPS AGENCE NATITINGOU",d:"Atacora",c:"NATITINGOU",r:"Dr Rofiath ODOUBIYI"},
  {t:"grossiste",n:"Centrale d\'Achat des Médicaments Vétérinaires (CAMEVET)",d:"Littoral",c:"COTONOU",r:""},
  {t:"grossiste",n:"Groupe Veto Services SA",d:"Littoral Et Atlantique",c:"COTONOU ET HEVIE",r:""},
  {t:"grossiste",n:"Société Vétérinaire du Bénin (SVB)",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie",n:"PHARMAQUICK BY ABT SA",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie",n:"COPHARBIOTEC",d:"Atlantique",c:"OUIDAH",r:"Dr Marcel HOUNDONNOUGBO"},
  {t:"industrie",n:"API-BENIN",d:"Zou",c:"ZOGBODOMEY",r:""},
  {t:"industrie",n:"KOFOYAK",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie",n:"SOFTCARE BENIN LIMITED",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie",n:"LABEL BENIN",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie",n:"LES BENIES DE DIEU E FILS",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie",n:"SOBECO SA",d:"Atlantique",c:"ABOMEY-CALAVI",r:""},
  {t:"depot",n:"BANAME",d:"Zou",c:"ZAGNANADO",r:"HOUNNONKPEVI Adolfe"},
  {t:"depot",n:"PENIEL DE MOUGNON",d:"Zou",c:"ABOMEY",r:"ALLOKPE Edwige"},
  {t:"depot",n:"SAINT MICHEL DE DAN (DJIDJA)",d:"Zou",c:"DJIDJA",r:"ATANNON Camille"},
  {t:"depot",n:"KPEDEKPO",d:"Zou",c:"ZAGNANADO",r:"ZOUIHOUE Chimène"},
  {t:"depot",n:"PENIEL AGOUNA",d:"Zou",c:"DJIDJA",r:"AGBOTOUSSO Pélagie"},
  {t:"depot",n:"BETEROU",d:"Borgou",c:"TCHAOUROU",r:"YERIMA Jacqueline"},
  {t:"depot",n:"BORI",d:"Borgou",c:"N\'DALI",r:"ARASSIMOU ABDOULAYE"},
  {t:"depot",n:"KIKA",d:"Borgou",c:"TCHAOUROU",r:"BIAOU Florence"},
  {t:"depot",n:"LA PATIENCE DE SONNOUMON",d:"Borgou",c:"N\'DALI",r:"DAOUDA Labiatou"},
  {t:"depot",n:"PAPANE",d:"Borgou",c:"TCHAOUROU",r:"DJIBRIL Zafira"},
  {t:"depot",n:"TCHATCHOU",d:"Borgou",c:"TCHAOUROU",r:"BIAOU Adeline"},
  {t:"depot",n:"KOKORO",d:"Collines",c:"OUESSE",r:"SOGLO Hortense"},
  {t:"depot",n:"PRINCIPAL DE GOME",d:"Zou",c:"GLAZOUE",r:"OBOSSOU Espérance"},
  {t:"depot",n:"ILLARA",d:"Plateau",c:"KETOU",r:"Dr KOUKPEMEDJI Louis"},
  {t:"depot",n:"ITA-DJEBOU",d:"Plateau",c:"ADJA-OUERE",r:"Dr ELEGBEDE O. Pancras"},
  {t:"depot",n:"KOUREL",d:"Borgou",c:"KALALE",r:"Dr BACHABI Abdoulaye"},
  {t:"depot",n:"BIRO",d:"Borgou",c:"NIKKI",r:"Dr BACHABI Abdoulaye"},
  {t:"depot",n:"INA",d:"Borgou",c:"BEMBEREKE",r:"Dr ZIME Rachade"},
  {t:"depot",n:"ALAFIA",d:"Borgou",c:"BEMBEREKE",r:"OSSENI Issiakou"},
  {t:"depot",n:"SAFARI",d:"Borgou",c:"PERERE",r:"Dr BACHABI Abdoulaye"},
  {t:"industrie_artisanale",n:"ORIGINE TERRE",d:"Atlantique",c:"ABOMEY CALAVI",r:"Evelyne Caludia YEWADAN TOGBE"},
  {t:"industrie_artisanale",n:"ZECM",d:"Atlantique",c:"ABOMEY CALAVI",r:"ZINZINDOHOUE Eunice"},
  {t:"industrie_artisanale",n:"CALVITEX",d:"Littoral",c:"COTONOU",r:"Rose-Marie HOUNTONDJI"},
  {t:"industrie_artisanale",n:"SWEET LIFE AFRICA",d:"Atlantique",c:"ABOMEY CALAVI",r:""},
  {t:"industrie_artisanale",n:"SAFA ET MARWA",d:"Littoral",c:"ABOMEY CALAVI",r:"Abiba OMAR MOUSSA"},
  {t:"industrie_artisanale",n:"AVALU UPHARMA BIO",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie_artisanale",n:"DERMA PIO",d:"Atlantique",c:"ALLADA",r:"Prudencia GBAGUIDI"},
  {t:"industrie_artisanale",n:"ETS WIN LIFE",d:"Atlantique",c:"ABOMEY CALAVI",r:"Bruno TOGNON"},
  {t:"industrie_artisanale",n:"GENERATION BIEN ETRE",d:"Atlantique",c:"ABOMEY CALAVI",r:"Yao Raphael TCHIDIME"},
  {t:"industrie_artisanale",n:"MDS EXPRESS",d:"Littoral",c:"COTONOU",r:"Miranda Ifèshéyi de SOUZA"},
  {t:"industrie_artisanale",n:"MAN CHA ALLAH",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie_artisanale",n:"ILERAMI",d:"Littoral",c:"COTONOU",r:"Scholastique COUTHON"},
  {t:"industrie_artisanale",n:"BOOST SANTE",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie_artisanale",n:"BIO WORLD SARL",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie_artisanale",n:"BISKARA SARL",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie_artisanale",n:"ETS ZH",d:"Littoral",c:"COTONOU",r:""},
  {t:"industrie_artisanale",n:"DERMOPHARM",d:"Littoral",c:"",r:""},
  {t:"industrie_artisanale",n:"LABORATOIRES MFK",d:"Littoral",c:"COTONOU",r:"Dr Jérôme MEDEGAN FAGLA"},
  {t:"industrie_artisanale",n:"ONG FAMASEP",d:"Atlantique",c:"Zè",r:"Léonie AKPADO"},
  {t:"industrie_artisanale",n:"LAUDATO SI - LA PROVIDENCE",d:"Plateau",c:"IFANGNI",r:"M. DARLING Guidigan"},
  {t:"industrie_artisanale",n:"KOOSU BABOU",d:"Atlantique",c:"ABOMEY CALAVI",r:"Maxime SALLAN"},
  {t:"industrie_artisanale",n:"ONG SANTE POUR TOUS",d:"Littoral",c:"COTONOU",r:"GBEDIGA Barnabé"},
  {t:"industrie_artisanale",n:"GROUPE PEPITE D\'OR",d:"Atlantique",c:"OUIDAH",r:"ADJADOGBEDJI Sébatiennne"},
  {t:"industrie_artisanale",n:"BENIN BENI COSMETICS",d:"Atlantique",c:"ABOMEY CALAVI",r:"Mme Rébéca SOHIZOUN"},
  {t:"industrie_artisanale",n:"KOFOYAK",d:"Ouémé",c:"SEME-KPODJI",r:"Mme Adidjatou YESSOUFOU"},
  {t:"industrie_artisanale",n:"LABEL GROUP INTERNATIONAL",d:"Ouémé",c:"SEME-KPODJI",r:"Msr Valère KPOVIESSI"},
  {t:"industrie_artisanale",n:"LES BENIES DE DIEUR ET FILS",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie_artisanale",n:"SOFTCARE",d:"Ouémé",c:"SEME-KPODJI",r:""},
  {t:"industrie_artisanale",n:"GRANDE ROYALE",d:"Ouémé",c:"PORTO-NOVO",r:""},
  {t:"agence_representation",n:"BOS TRINITE",d:"Littoral",c:"Cotonou",r:"M. BOSSOU Roger-luc"},
  {t:"agence_representation",n:"CFMA PHARMA Sarl",d:"Littoral",c:"Cotonou",r:"M. HOUEDJI Yvon"},
  {t:"agence_representation",n:"AGM PROMO",d:"Atlantique",c:"Abomey-Calavi",r:"ALIOZA Gilles-Marc"},
  {t:"agence_representation",n:"AIRECO SARL",d:"Littoral",c:"Cotonou",r:"ZANNOU Gabriel"},
  {t:"agence_representation",n:"BADER PHARMA",d:"Littoral",c:"Cotonou",r:"BADAROU Razack Okawe"},
  {t:"agence_representation",n:"CITE DE RECONCILIATION",d:"Atlantique",c:"Abomey-Calavi",r:"AHOBADE Setondji"},
  {t:"agence_representation",n:"ESDE PHARMA",d:"Atlantique",c:"Abomey-Calavi",r:"YAOVI Hermann"},
  {t:"agence_representation",n:"JORNAM PROMO",d:"Littoral",c:"Cotonou",r:"MENSAH Paul"},
  {t:"agence_representation",n:"OUSSOU PHARMA",d:"Ouémè",c:"Sèmè-podji",r:"FAGBOHOUN Hyppolite Samson"},
  {t:"agence_representation",n:"PHARMACOL",d:"Littoral",c:"Cotonou",r:"AGEMAVO Jean Eudes"},
  {t:"agence_representation",n:"SEDJRO PHARMA",d:"Atlantique",c:"Abomey-Calavi",r:"AKPATA Fiacre"},
  {t:"agence_representation",n:"SERHENA BIOMEDICAL",d:"Ouémè",c:"Sèmè-podji",r:"YEKPE Annette"},
  {t:"agence_representation",n:"APM PHARMA",d:"Littoral",c:"Cotonou",r:"MENSAH Joël"},
  {t:"agence_representation",n:"COMVIA HEALTH  SOLUTIONS",d:"Littoral",c:"Cotonou",r:"TOPANOU Arabel"},
  {t:"agence_representation",n:"ELITE PHARMA Sarl",d:"Atlantique",c:"Abomey-Calavi",r:"HOLOGAN Prisca"},
  {t:"agence_representation",n:"ENERGIA PROMO",d:"Littoral",c:"Cotonou",r:"COCOU Bernadin"},
  {t:"agence_representation",n:"GOLD PHARMA",d:"Littoral",c:"Cotonou",r:"COMAHOUE Sewa"},
  {t:"agence_representation",n:"MERVEILLES ET QUALITE",d:"Littoral",c:"Cotonou",r:"FONTECLOUNON Donatien"},
  {t:"agence_representation",n:"REMED PHARMA PLUS",d:"Atlantique",c:"",r:"HOUNSA Alexandre"},
  {t:"agence_representation",n:"SPEED GOOD BENIN Sarl",d:"Littoral",c:"Cotonou",r:"DAIZO Dominique"},
  {t:"agence_representation",n:"SUN INTERNATIONAL",d:"Littoral",c:"Cotonou",r:"SOUNOUVOU Espoir"},
];

export function searchEstablishments(query, limit = 15) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return ESTABLISHMENTS.filter(e => e.n.toLowerCase().includes(q) || e.r.toLowerCase().includes(q) || e.c.toLowerCase().includes(q)).slice(0, limit);
}

export function getEstabByDeptCommune(dept, commune) {
  return ESTABLISHMENTS.filter(e => (!dept || e.d === dept) && (!commune || e.c.toLowerCase() === commune.toLowerCase()));
}

const TYPE_LABELS = {officine:'Officine',grossiste:'Grossiste',industrie:'Industrie',depot:'Depot pharmaceutique',industrie_artisanale:'Industrie artisanale',agence_representation:'Agence de representation'};
export function typeLabel(t) { return TYPE_LABELS[t] || t; }