// ═══════════════════ JS FALLBACK GRIDS ═══════════════════
export function buildAllGridsJS(){let id=0;const n=(r,d,p)=>({id:++id,reference:r,description:d,pre_opening:p});const it=(r,d)=>n(r,d,false);const pr=(r,d)=>n(r,d,true);
const off={id:'officine',name:'Inspection Officine',code:'IP-F-0018',version:'1',description:"Grille d'inspection des officines",icon:'💊',color:'#DC2626',sections:[
{id:1,title:"Renseignements généraux",items:[pr("Loi 2021-03 Art 46","Identification de la structure"),it("Loi 2021-03 Art 61,62","Mode d'acquisition"),it("","Statut ou mode d'exploitation"),it("Loi 2021-03 Art 62","Quitus d'exploitation"),it("","Adresse, Tel, Mail"),it("Loi 2021-03 Art 59,62","Localisation"),it("","Correspondance attribution/site"),it("Loi 2021-03 Art 65","Horaires affichés"),it("BPDisp 1.14","Service de garde")]},
{id:2,title:"SMQ",items:[pr("BPDisp 1.3-1.5","SMQ en place ?"),pr("BPDisp 1.6","RMQ désigné ?"),pr("BPDisp 1.16","Gestion risque qualité"),it("BPDisp 1.15-1.17","Sécurité du patient"),pr("BPDisp 1.31a,f","Moyens acte pharmaceutique"),pr("BPDisp 1.31g","Traçabilité")]},
{id:3,title:"Personnel",items:[pr("BPDisp 2.2","Personnel suffisant"),pr("BPDisp 2.3","Organigramme"),pr("BPDisp 2.4","Inscription Ordre"),it("BPDisp 2.9,2.10","Présence pharmacien"),it("Décret 1296","Conditions assistance"),it("BPDisp 2.5","Remplacement"),it("BPDisp 2.11","Badge"),it("BPDisp 2.12","Entretien annuel"),pr("BPDisp 2.8","Formation initiale"),pr("BPDisp 2.14-2.20","Formation continue"),it("BPDisp 2.18","Suivi formations"),it("BPDisp 2.21","Hygiène")]},
{id:4,title:"Documentation",items:[pr("BPDisp 3.4-3.9","Ordonnancier (10 ans)"),pr("","Registre stupéfiants"),pr("BPDisp 3.6,3.7","Registre dérivés sang"),pr("BPDisp 3.4a","Registre préparations"),it("BPDisp 3.11,3.12","Copies ordonnances"),pr("","Documents officiels"),pr("BPDisp 1.22-1.28","Procédures qualité"),pr("BPDisp 3.16-3.20","Maîtrise documentaire"),pr("BPDisp 3.22","Évaluation périodique"),pr("BPDisp 3.23","Gestion modifications"),pr("BPDisp 3.21","Documents approuvés"),it("BPDisp 3.24","Gestion diffusion"),it("BPDisp 3.25","Cycle de vie documents"),it("BPDisp 3.13","Enregistrements"),it("BPDisp 2.13","Archives"),it("BPDisp 3.28","Documents santé publique")]},
{id:5,title:"Locaux et équipements",items:[pr("Loi Art 46","Emblème, enseigne"),pr("BPDisp 4.1-4.22","Propreté locaux"),pr("BPDisp 4.7","Stockage dangereux"),pr("BPDisp 4.7,4.8","Sécurité"),pr("BPDisp 4.6","Disposition médicaments"),pr("BPDisp 3.15,4.10","Zone préparation"),pr("BPDisp 4.18","Éclairage, température"),pr("BPDisp 4.21","Sanitaires"),pr("BPDisp 1.7,4.23","Matériel qualifié"),it("BPDisp 4.24","Entretien matériel"),it("BPDisp 4.25","Étalonnage"),it("BPDisp 4.26","SI validé"),it("BPDisp 4.30","Contrat SI"),it("BPDisp 4.33","Accès informatique"),it("BPDisp 4.34","Sauvegarde"),it("BPDisp 4.36","Mesures remplacement"),it("Décret 1296","Vente en ligne")]},
{id:6,title:"Approvisionnement",items:[it("BPDisp 5.1,5.2","Stock sécurité"),it("BPDisp 5.3","Commerce hors liste"),it("BPDisp 5.7-5.9","Commandes"),it("Loi 97-025","Stupéfiants souches"),it("BPDisp 5.10","Transport réception"),it("BPDisp 5.11","Réception hors heures"),pr("BPDisp 5.12","Colis vérifiés")]},
{id:7,title:"Sous-traitance",items:[it("Annexe 6.13","Contrat et audit")]},
{id:8,title:"Dispensation",items:[it("Loi 97-025","Substances vénéneuses"),it("","1ère délivrance < 3 mois"),it("","Renouvellement max 12 mois"),it("BPDisp 7.14","Acte intégral"),it("BPDisp 7.16","Surveillance"),it("BPDisp 7.17","Substitution"),it("BPDisp 7.18","Refus si risque"),it("BPDisp 7.19-7.42","Acte complet"),it("BPDisp 7.34","Mentions exécution"),it("","Dispensation chronique"),it("","Vétérinaires"),it("","DM, cosmétiques"),it("BPDisp 7.36","Stupéfiants"),it("BPDisp 7.43-7.48","Conseil"),it("Loi Art 77","Notification EI"),it("BPDisp 7.52","Vente en ligne"),it("","Emballage"),it("BPDisp 7.65","Réduction"),it("BPDisp 7.60","Livraison domicile")]},
{id:9,title:"Retours/Réclamations",items:[it("BPDisp 8.3","Gestion retours"),it("BPDisp 8.4","MNU"),it("BPDisp 8.5","Produits récupérés"),it("BPDisp 8.12","Retraits")]},
{id:10,title:"Déchets",items:[it("BPDisp 9.2","Gestion déchets")]},
{id:11,title:"Préparations",items:[pr("BPDisp 3.4-a","Personnel et local"),it("","Matières premières"),it("","Procédures"),it("BPDisp 3.4","Étiquetage"),it("","Libération")]},
{id:12,title:"Publicité/PSQIF",items:[it("Ord 73-30","Publicité"),it("Loi Art 54","Pratique illégale"),it("BPDisp 5.5","PSQIF")]},
{id:13,title:"Auto-inspection",items:[it("BPDisp 10.1","Couverture SMQ"),it("","Enregistrements"),it("","Mesures correctives"),it("","Suivi")]}]};
id=0;
const gro={id:'grossiste',name:'Inspection Grossiste-Répartiteur',code:'IP-FO-0002',version:'1',description:"Grille grossiste-répartiteur selon BPD/UEMOA",icon:'🏭',color:'#DC2626',sections:[
{id:1,title:"Organisation et gestion",items:[pr("BPD/I 1.01","Autorisé ? Pharmacien ?"),pr("BPD/I 1.02","Organigramme"),pr("BPD/I 1.03","Pharmacien par site"),it("BPD/I 1.04","Autorité et ressources"),it("BPD/I 1.05,1.06","Conflits d'intérêts"),it("BPD/I 1.07","Descriptions de fonction"),it("BPD/I 1.08","Sous-traitance"),it("BPD/I 1.09","Sécurisation")]},
{id:2,title:"Gestion de la qualité",items:[pr("BPD/I 1.10,1.11","Système AQ ?"),pr("BPD/I 1.13","Responsabilité partagée"),it("BPD/I 1.14","E-commerce traçabilité"),pr("BPD/I 1.15","Fournisseurs approuvés"),pr("BPD/I 1.16","Traçabilité"),pr("BPD/I 1.18","Procédures opérations")]},
{id:3,title:"Personnel",items:[pr("BPD/I 1.19","Personnel formé BPD"),pr("BPD/I 1.20","Personnel clé compétent"),pr("BPD/I 1.21","Effectifs suffisants"),it("BPD/I 1.22","Qualifications"),pr("BPD/I 1.23","Formation continue"),it("BPD/I 1.24","Formations enregistrées"),it("BPD/I 1.25","Formation dangereux"),it("BPD/I 1.26","Vêtements"),it("BPD/I 1.27","Hygiène"),it("BPD/I 1.28","Détention non autorisée"),it("BPD/I 1.29","Détournements"),it("Décret 2024-1301","Pharmacien 5 ans exp."),it("Loi 2021-03","Pharmaciens adjoints")]},
{id:4,title:"Documentation",items:[pr("BPD/I 1.30","Instructions écrites"),pr("BPD/I 1.31","Documents approuvés"),it("BPD/I 1.32","Contenu clair"),it("BPD/I 1.33","Revue régulière"),pr("BPD/I 1.34","Enregistrements accessibles"),it("BPD/I 1.35","Données protégées"),it("BPD/I 1.36,1.37","SI validé")]},
{id:5,title:"Réclamations",items:[it("BPD/I 1.38","Procédure réclamations"),it("BPD/I 1.39","Enregistrement examen"),it("BPD/I 1.40","Personne responsable"),it("BPD/I 1.42","Mesures révisées")]},
{id:6,title:"Rappels",items:[it("BPD/I 1.43","Système de rappel"),it("BPD/I 1.44","Rappel immédiat"),it("BPD/I 1.45","Évaluation risque"),it("BPD/I 1.47","Traçabilité destinataires"),it("BPD/I 1.48","Produits rappelés isolés")]},
{id:7,title:"Sous-traitance",items:[it("BPD/I 1.49","Contrat écrit"),it("BPD/I 1.50","Sous-traitant autorisé"),it("BPD/I 1.51","Audits réguliers")]},
{id:8,title:"Auto-inspections",items:[it("BPD/I 1.53","Auto-inspections régulières"),it("BPD/I 1.54","Programme complet"),it("BPD/I 1.55","Rapports et actions"),it("BPD/I 1.56","Actions correctives")]},
{id:9,title:"Locaux",items:[pr("BPD/I 2.01","Locaux vastes et entretenus"),pr("BPD/I 2.02","Zones conditions stockage"),pr("BPD/I 2.03","Anti-nuisibles"),pr("BPD/I 2.04","Accès restreint"),pr("BPD/I 2.05","Disposition logique"),pr("BPD/I 2.06","Capacité suffisante")]},
{id:10,title:"Réception",items:[pr("BPD/I 2.07","Quais protégés"),pr("BPD/I 2.08","Zone quarantaine"),pr("BPD/I 2.09","Produits refusés séparés")]},
{id:11,title:"Stockage",items:[pr("BPD/I 2.10","Stockage ordonné FEFO"),pr("BPD/I 2.11","Propreté"),pr("BPD/I 2.12","Conditions spéciales"),pr("BPD/I 2.13","Surveillance T°"),it("BPD/I 2.14","Mapping température"),pr("BPD/I 2.15","Stupéfiants sécurisés"),it("BPD/I 2.16","Zones produits dangereux")]},
{id:12,title:"Véhicules et matériels",items:[it("BPD/I 2.17","Véhicules adaptés"),it("BPD/I 2.18","Entretien documenté"),it("BPD/I 2.19","Surveillance T° véhicules")]},
{id:13,title:"Approvisionnement",items:[pr("BPD/I 3.01","Fournisseurs autorisés"),pr("BPD/I 3.02","Enregistrements"),it("BPD/I 3.03","Vérifications réception"),it("Loi 97-025","Stupéfiants souches")]},
{id:14,title:"Opérations de stockage",items:[it("BPD/I 3.05","Statuts produits"),it("BPD/I 3.07","Conditions AMM"),it("BPD/I 3.09","Stupéfiants sécurisés"),it("BPD/I 3.10","Rotation FEFO"),it("BPD/I 3.11","Péremptions vérifiées"),it("BPD/I 3.13","Inventaires documentés"),it("BPD/I 3.14","Inventaires trimestriels")]},
{id:15,title:"Préparation commandes",items:[it("BPD/I 3.15","Procédure et contrôle"),it("BPD/I 3.16","Documents accompagnement"),it("BPD/I 3.17","Traçabilité"),it("BPD/I 3.18","Vente aux autorisés")]},
{id:16,title:"Expédition/Transport",items:[it("BPD/I 4.01","Emballage conforme"),it("BPD/I 4.02","FEFO étiquetage"),it("BPD/I 4.04-4.08","Chaîne du froid"),it("BPD/I 4.09","Anti-vol"),it("BPD/I 4.11","Véhicules propres"),it("BPD/I 4.15","Calendriers livraison"),it("BPD/I 4.17","Vérification livraison")]},
{id:17,title:"Produits refusés/retournés",items:[it("BPD/I 5.01","Refusés séparés"),it("BPD/I 5.02","Enregistrements retours"),it("BPD/I 5.03","Destruction traçable"),it("BPD/I 5.04","Retours quarantaine"),it("BPD/I 5.06","Falsifiés signalés")]},
{id:18,title:"Contrefaçon/PSQIF",items:[it("BPD/I 6.01","Système PSQIF"),it("BPD/I 6.04","Vérification authenticité"),it("BPD/I 6.05","Personnel formé"),it("Loi 2021-03","Notification autorités")]}]};
return[off,gro];}
